# Generated by Django 5.2.14 on 2026-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
