# Generated by Django 5.2.14 on 2026-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=80)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('language', 'Programming Language'), ('other', 'Other')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
