# Generated by Django 5.2.14 on 2026-05-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/files/')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
